jira-translator-cdevents : translate jira issue and worklog events into ticket CDEvents
cdevents/jira-translator pull request #1
Opened 2024-07-26 13:13 UTC by rjalander

This PR includes the changes for a plugin implementation of `EventTranslator` interface that is exposed by [CDEvents Webhook Adapter](https://github.com/cdevents/webhook-adapter) to translate jira events into CDEvents.

Below are the Jira events that are currently have mappings with CDEvents and are supported by this translator.

| CDEvent Type  | Jira Event Type  |
| :------------ |:-------------------|
|  dev.cdevents.ticket.created| issue_created |
|  dev.cdevents.ticket.updated   | issue_updated    |
|  dev.cdevents.ticket.updated   | issue_commented    |
|  dev.cdevents.ticket.updated   | issue_assigned    |
|  dev.cdevents.ticket.updated   | issue_work_logged    |
|  dev.cdevents.ticket.updated   | issue_worklog_updated    |
|  dev.cdevents.ticket.updated   | issue_worklog_deleted    |
|  dev.cdevents.ticket.closed    | issue_generic     |

Note: 
- This implementation is as per the [RFC proposed](https://github.com/cdevents/community/pull/45)
- CDEvents Ticket related events are created from [sd-go main](https://github.com/cdevents/sdk-go/tree/main), will be updated once sdk-go v0.4 released
- `webhook-adapter` dependency also will be updated once sdk-go v0.4 released

Signed-off-by: Jalander Ramagiri @rjalander

2024-08-29 15:42 UTC, xibz requested changes
Most of my comments are very minor, so should be able to be resolved fairly quickly

2024-08-29 15:42 UTC, xibz commented on pkg/jira/event.go
> +	return
```suggestion
	return &JiraEvent{event}
```

2024-08-29 15:42 UTC, xibz commented on pkg/jira/event.go
> +func NewJiraEvent(event string) (pEvent *JiraEvent) {
```suggestion
func NewJiraEvent(event string) *JiraEvent {
```

2024-08-29 15:42 UTC, xibz commented on pkg/jira/event.go
> +type JiraEvent struct {
If it is only a single string field, we can do something like this instead

```go
type JiraEvent string
```

2024-08-29 15:42 UTC, xibz requested changes
Most of my comments are very minor, so should be able to be resolved fairly quickly

2025-05-04 13:09 UTC, joeblew999 commented
Hey @rjalander :)

 Is this abandoned ?    Wondering how we get this in. Would be cool.

2025-05-04 13:14 UTC, xibz commented
@joeblew999 Howdy! @rjalander has moved to a different company, but this is something we can pick up in CDEvents. Ill take a look at this and see if I can help get this in.

We have an implantation SIG that discusses topics like this which occurs every other Tuesday. Take a look at this calendar: https://calendar.google.com/calendar/u/0/embed?src=linuxfoundation.org_mhf0kmgedn67ihni8r129avp24@group.calendar.google.com&ctz=UTC

It includes all CDF project, but the implementation SIG is also in there.

2025-05-04 13:15 UTC, afrittoli commented
@joeblew999 The original contributor (@rjalander) is not working on this project anymore, unfortunately. If you wanted to pick this up and continue the work, it would be very nice, the contribution would be most welcome.

2025-05-04 13:56 UTC, joeblew999 commented
Hey @rjalander @xibz 

that was quick !

I cant help right now. 

Tell you what would be useful is where the big picture roadmap is.  CD Events are seriously useful for Secure SBOM auditing.

2026-05-15 20:00 UTC, merged